{"name": "test_data_save_right[SJSL_003-{ \"data\":{\"idcardno\":\"110105200001021452\",\"sex\":\"男\",\"birthday\":\"2000-01-02\"},\n    \"nonce\": \"one3874\",\n    \"timestamp\": 1941761698000,\n    \"sign\": \"d8d1d2f27030ab36d69b155bb0825189e3b55c1873e64b122dde7c0df140acd4\",\n    \"legerId\":48,\n    \"chainId\":49,\n    \"appId\": \"rRHm0G\",\n    \"clusterId\": 60\n}-{\n    \"code\": 200,\n    \"msg\": \"成功\",\n    \"data\": {\n        \"data\": \"48ca10e36edd138ff6d802eaa14c44323cd46c90a8186445840409c6f04c1c5e\"\n    },\n    \"timestamp\": 1626764041829,\n    \"success\": true\n}]", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n3 Failed Assumptions:\n\ntest_openApi.py:56: AssumptionFailure\n>>\tpytest.assume(res[\"code\"] == expData[\"code\"])  # int\nAssertionError: assert False\n\ntest_openApi.py:57: AssumptionFailure\n>>\tpytest.assume(res[\"msg\"] == expData[\"msg\"])  # str\nAssertionError: assert False\n\ntest_openApi.py:58: AssumptionFailure\n>>\tpytest.assume(res[\"success\"] == expData[\"success\"])  # bool\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               3 Failed Assumptions:\nE               \nE               test_openApi.py:56: AssumptionFailure\nE               >>\tpytest.assume(res[\"code\"] == expData[\"code\"])  # int\nE               AssertionError: assert False\nE               \nE               test_openApi.py:57: AssumptionFailure\nE               >>\tpytest.assume(res[\"msg\"] == expData[\"msg\"])  # str\nE               AssertionError: assert False\nE               \nE               test_openApi.py:58: AssumptionFailure\nE               >>\tpytest.assume(res[\"success\"] == expData[\"success\"])  # bool\nE               AssertionError: assert False\n\n..\\venv\\lib\\site-packages\\six.py:718: FailedAssumption"}, "parameters": [{"name": "caseNum", "value": "'SJSL_003'"}, {"name": "inData", "value": "'{ \"data\":{\"idcardno\":\"110105200001021452\",\"sex\":\"男\",\"birthday\":\"2000-01-02\"},\n    \"nonce\": \"one3874\",\n    \"timestamp\": 1941761698000,\n    \"sign\": \"d8d1d2f27030ab36d69b155bb0825189e3b55c1873e64b122dde7c0df140acd4\",\n    \"legerId\":48,\n    \"chainId\":49,\n    \"appId\": \"rRHm0G\",\n    \"clusterId\": 60\n}'"}, {"name": "expData", "value": "'{\n    \"code\": 200,\n    \"msg\": \"成功\",\n    \"data\": {\n        \"data\": \"48ca10e36edd138ff6d802eaa14c44323cd46c90a8186445840409c6f04c1c5e\"\n    },\n    \"timestamp\": 1626764041829,\n    \"success\": true\n}'"}], "start": 1627020574145, "stop": 1627020574117, "uuid": "c7823f93-166c-4fdd-818b-af0a84f8258a", "historyId": "29b7d6976ec995d4b004976feb0dec78", "testCaseId": "4fb152223fa39a590b66f51ef9133b0c", "fullName": "testcase.test_openApi.TestOpenAPI#test_data_save_right", "labels": [{"name": "feature", "value": "数据上链-正常流"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_openApi"}, {"name": "subSuite", "value": "TestOpenAPI"}, {"name": "host", "value": "DESKTOP-5UFTAI3"}, {"name": "thread", "value": "14072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_openApi"}]}